"""Add departments, students, and made some changes in users models

Revision ID: 3daa72ba9cd1
Revises: a1f62cd8aa21
Create Date: 2026-08-08 00:42:07.280200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3daa72ba9cd1'
down_revision: Union[str, Sequence[str], None] = 'a1f62cd8aa21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dept_code', sa.String(length=10), nullable=False),
    sa.Column('dept_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('dept_code')
    )
    op.create_index(op.f('ix_departments_dept_code'), 'departments', ['dept_code'], unique=False)
    op.create_index(op.f('ix_departments_dept_name'), 'departments', ['dept_name'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.Integer(), sa.Identity(always=False, start=1001), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(length=10), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['dept_code'], ['departments.dept_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_roll_no'), 'students', ['roll_no'], unique=True)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_roll_no'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_departments_dept_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_dept_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
