"""Add a institute_id column in students table

Revision ID: 6cbbb0c050e7
Revises: ed00aa852818
Create Date: 2026-09-10 12:23:01.927563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbbb0c050e7'
down_revision: Union[str, Sequence[str], None] = 'ed00aa852818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('institute_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'institutes', ['institute_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'institute_id')
    # ### end Alembic commands ###
