"""Change in department writing structure

Revision ID: 90aceef8880e
Revises: 882231a72006
Create Date: 2026-08-13 10:57:27.802557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90aceef8880e'
down_revision: Union[str, Sequence[str], None] = '882231a72006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('dept_code', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('students_department_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'departments', ['dept_code'], ['dept_code'])
    op.drop_column('students', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_department_fkey'), 'students', 'departments', ['department'], ['dept_code'])
    op.drop_column('students', 'dept_code')
    # ### end Alembic commands ###
