"""Add some database models and updated some of the existing database models to suit latest database design patterns

Revision ID: 90dfbc8b66d8
Revises: 60f5fa7069df
Create Date: 2026-08-08 19:27:41.800888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90dfbc8b66d8'
down_revision: Union[str, Sequence[str], None] = '60f5fa7069df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('department', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('faculty_dept_code_fkey'), 'faculty', type_='foreignkey')
    op.create_foreign_key(None, 'faculty', 'departments', ['department'], ['dept_name'])
    op.drop_column('faculty', 'dept_code')
    op.add_column('students', sa.Column('first_name', sa.String(length=25), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(length=25), nullable=False))
    op.add_column('students', sa.Column('dob', sa.Date(), nullable=False))
    op.add_column('students', sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sexenum'), nullable=False))
    op.add_column('students', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('students', sa.Column('date_of_admission', sa.Date(), nullable=False))
    op.add_column('students', sa.Column('department', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('start_batch_year', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('end_batch_year', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False))
    op.drop_constraint(op.f('students_dept_code_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'departments', ['department'], ['dept_name'])
    op.drop_column('students', 'dept_code')
    op.drop_column('students', 'admission_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('admission_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('dept_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_dept_code_fkey'), 'students', 'departments', ['dept_code'], ['dept_code'])
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    op.drop_column('students', 'end_batch_year')
    op.drop_column('students', 'start_batch_year')
    op.drop_column('students', 'department')
    op.drop_column('students', 'date_of_admission')
    op.drop_column('students', 'address')
    op.drop_column('students', 'sex')
    op.drop_column('students', 'dob')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    op.add_column('faculty', sa.Column('dept_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'faculty', type_='foreignkey')
    op.create_foreign_key(op.f('faculty_dept_code_fkey'), 'faculty', 'departments', ['dept_code'], ['dept_code'])
    op.drop_column('faculty', 'department')
    # ### end Alembic commands ###
