"""Add programs table and some minor changes into the database

Revision ID: 95788cbfcd72
Revises: 9b3a32181b59
Create Date: 2026-09-11 20:57:36.981001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95788cbfcd72'
down_revision: Union[str, Sequence[str], None] = '9b3a32181b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=15), nullable=False),
    sa.Column('program_name', sa.String(length=100), nullable=False),
    sa.Column('degree', sa.String(length=30), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.CheckConstraint('duration_years > 0', name='ck_program_duration'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institute_id', 'program_code', name='uq_program_institute_code')
    )
    op.create_index(op.f('ix_programs_department_id'), 'programs', ['department_id'], unique=False)
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_index(op.f('ix_programs_institute_id'), 'programs', ['institute_id'], unique=False)
    op.create_index(op.f('ix_programs_program_code'), 'programs', ['program_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programs_program_code'), table_name='programs')
    op.drop_index(op.f('ix_programs_institute_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_department_id'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
