"""Add programs table and some minor changes into the database


Revision ID: 9b3a32181b59
Revises: 0045376311ad
Create Date: 2026-09-11 20:55:55.307195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3a32181b59'
down_revision: Union[str, Sequence[str], None] = '0045376311ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_faculty_dept_id'), 'faculty', ['dept_id'], unique=False)
    op.create_index(op.f('ix_faculty_institute_id'), 'faculty', ['institute_id'], unique=False)
    op.create_index(op.f('ix_faculty_role_id'), 'faculty', ['role_id'], unique=False)
    op.drop_index(op.f('ix_students_roll_no'), table_name='students')
    op.create_index(op.f('ix_students_roll_no'), 'students', ['roll_no'], unique=False)
    op.create_index(op.f('ix_students_dept_id'), 'students', ['dept_id'], unique=False)
    op.create_index(op.f('ix_students_institute_id'), 'students', ['institute_id'], unique=False)
    op.create_unique_constraint('uq_student_institute_roll_no', 'students', ['institute_id', 'roll_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_institute_roll_no', 'students', type_='unique')
    op.drop_index(op.f('ix_students_institute_id'), table_name='students')
    op.drop_index(op.f('ix_students_dept_id'), table_name='students')
    op.drop_index(op.f('ix_students_roll_no'), table_name='students')
    op.create_index(op.f('ix_students_roll_no'), 'students', ['roll_no'], unique=True)
    op.drop_index(op.f('ix_faculty_role_id'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_institute_id'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_dept_id'), table_name='faculty')
    # ### end Alembic commands ###
