"""Add departments, students, and made some changes in users models

Revision ID: a1f62cd8aa21
Revises: b93a3fe03e04
Create Date: 2026-08-08 00:27:14.232090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f62cd8aa21'
down_revision: Union[str, Sequence[str], None] = 'b93a3fe03e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
