"""Did whole database connections of relationships by institutes

Revision ID: a220a7203509
Revises: c4a7b4d5ce37
Create Date: 2026-09-10 16:23:08.090308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a220a7203509'
down_revision: Union[str, Sequence[str], None] = 'c4a7b4d5ce37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('departments', sa.Column('institute_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_foreign_key(None, 'departments', 'institutes', ['institute_id'], ['id'])
    op.add_column('faculty', sa.Column('institute_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'faculty', 'institutes', ['institute_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculty', type_='foreignkey')
    op.drop_column('faculty', 'institute_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_column('departments', 'institute_id')
    op.drop_column('departments', 'id')
    # ### end Alembic commands ###
