"""Add subjects table and some other database changes

Revision ID: a29812d49d1c
Revises: 95788cbfcd72
Create Date: 2026-09-12 00:30:12.173524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29812d49d1c'
down_revision: Union[str, Sequence[str], None] = '95788cbfcd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=15), nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institute_id', 'subject_code', name='uq_subject_institute_code')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_institute_id'), 'subjects', ['institute_id'], unique=False)
    op.create_index(op.f('ix_subjects_subject_code'), 'subjects', ['subject_code'], unique=False)
    op.create_index(op.f('ix_subjects_subject_name'), 'subjects', ['subject_name'], unique=False)
    op.create_table('program_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'subject_id', name='uq_program_subject')
    )
    op.create_index(op.f('ix_program_subjects_id'), 'program_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_program_subjects_program_id'), 'program_subjects', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_subjects_subject_id'), 'program_subjects', ['subject_id'], unique=False)
    op.add_column('students', sa.Column('program_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_students_program_id'), 'students', ['program_id'], unique=False)
    op.create_foreign_key(None, 'students', 'programs', ['program_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_program_id'), table_name='students')
    op.drop_column('students', 'program_id')
    op.drop_index(op.f('ix_program_subjects_subject_id'), table_name='program_subjects')
    op.drop_index(op.f('ix_program_subjects_program_id'), table_name='program_subjects')
    op.drop_index(op.f('ix_program_subjects_id'), table_name='program_subjects')
    op.drop_table('program_subjects')
    op.drop_index(op.f('ix_subjects_subject_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_subject_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_institute_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
