"""Add a institute_id column and relationships in students table

Revision ID: c4a7b4d5ce37
Revises: 6cbbb0c050e7
Create Date: 2026-09-10 12:52:42.590849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a7b4d5ce37'
down_revision: Union[str, Sequence[str], None] = '6cbbb0c050e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'institute_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'institute_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
