"""Remove global uniqueness of the department name

Revision ID: f37921ddaf6d
Revises: f5a512f5cd17
Create Date: 2026-09-17 18:01:22.191313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37921ddaf6d'
down_revision: Union[str, Sequence[str], None] = 'f5a512f5cd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_dept_name'), table_name='departments')
    op.create_index(op.f('ix_departments_dept_name'), 'departments', ['dept_name'], unique=False)
    op.create_unique_constraint('uq_department_institute_name', 'departments', ['institute_id', 'dept_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_department_institute_name', 'departments', type_='unique')
    op.drop_index(op.f('ix_departments_dept_name'), table_name='departments')
    op.create_index(op.f('ix_departments_dept_name'), 'departments', ['dept_name'], unique=True)
    # ### end Alembic commands ###
